import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import style from "./ui/page.module.css";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${style.page}`}>
        <Sidebar/>
        {children}
        </body>
    </html>
  );
}
